server:
  port: 8088

spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.131
  rabbitmq:
    host: 192.168.25.131
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳

ly:
  jwt:
    pubKeyPath: D:/heima/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称